"""Исследовательский comparison-layer для baseline-моделей.

Пакет содержит изолированный контур сравнения моделей на задаче
`host vs field`. Он не вмешивается в production pipeline и служит для
benchmark-отчётов под ВКР.
"""

from analysis.model_comparison.contracts import (
    DEFAULT_CV_CONFIG,
    DEFAULT_MLP_BASELINE_CONFIG,
    DEFAULT_SEARCH_CONFIG,
    SEARCH_REFIT_METRICS,
    BenchmarkSources,
    ClassSearchSummary,
    ComparisonProtocol,
    CrossValidationConfig,
    MLPBaselineConfig,
    ModelScoreFrames,
    ModelSearchSummary,
    RandomForestConfig,
    SearchConfig,
    SplitConfig,
)
from analysis.model_comparison.contrastive import (
    MAIN_CONTRASTIVE_MODEL_NAME,
    ContrastiveModelRun,
    build_contrastive_param_grid,
    fit_main_contrastive_model,
    fit_main_contrastive_model_with_search,
    run_main_contrastive_model,
    score_main_contrastive_model,
)
from analysis.model_comparison.data import (
    BenchmarkSplit,
    load_and_split_benchmark_dataset,
    load_benchmark_dataset,
    prepare_benchmark_dataset,
    split_benchmark_dataset,
)
from analysis.model_comparison.legacy_gaussian import (
    LEGACY_GAUSSIAN_MODEL_NAME,
    LegacyGaussianBaselineRun,
    build_legacy_gaussian_param_grid,
    fit_legacy_gaussian_baseline,
    fit_legacy_gaussian_baseline_with_search,
    run_legacy_gaussian_baseline,
    score_legacy_gaussian_baseline,
)
from analysis.model_comparison.manual_search import (
    evaluate_search_metric,
    rank_search_metric,
    run_manual_model_search,
)
from analysis.model_comparison.metrics import (
    build_classwise_metrics_frame,
    build_metrics_frame,
    precision_at_k,
    validate_scored_frame,
)
from analysis.model_comparison.mlp_baseline import (
    MLP_BASELINE_MODEL_NAME,
    MLPBaselineRun,
    build_mlp_param_grid,
    fit_mlp_baseline,
    fit_mlp_baseline_with_search,
    run_mlp_baseline,
    score_mlp_baseline,
    search_mlp_for_class,
)
from analysis.model_comparison.random_forest import (
    RANDOM_FOREST_MODEL_NAME,
    RandomForestBaselineRun,
    fit_random_forest_baseline,
    run_random_forest_baseline,
    score_random_forest_baseline,
)
from analysis.model_comparison.reporting import (
    DEFAULT_MODEL_COMPARISON_OUTPUT_DIR,
    build_comparison_classwise_frame,
    build_comparison_markdown,
    build_comparison_summary_frame,
    build_search_summary_frame,
    save_comparison_artifacts,
)
from analysis.model_comparison.snapshot import (
    DEFAULT_SNAPSHOT_OUTPUT_DIR,
    DEFAULT_SNAPSHOT_TOP_K,
    SnapshotComparisonResult,
    SnapshotModelRun,
    build_snapshot_markdown,
    build_snapshot_summary_frame,
    build_snapshot_top_frame,
    run_snapshot_comparison,
    save_snapshot_artifacts,
)
from analysis.model_comparison.tuning import (
    build_sklearn_search_scoring,
    build_stratified_kfold,
    build_stratify_labels,
    normalize_search_score,
    precision_at_k_from_proba,
    validate_cross_validation_inputs,
)

__all__ = [
    "BenchmarkSources",
    "BenchmarkSplit",
    "ClassSearchSummary",
    "ComparisonProtocol",
    "ContrastiveModelRun",
    "DEFAULT_CV_CONFIG",
    "DEFAULT_MLP_BASELINE_CONFIG",
    "DEFAULT_SEARCH_CONFIG",
    "CrossValidationConfig",
    "LEGACY_GAUSSIAN_MODEL_NAME",
    "LegacyGaussianBaselineRun",
    "MAIN_CONTRASTIVE_MODEL_NAME",
    "MLPBaselineConfig",
    "MLP_BASELINE_MODEL_NAME",
    "MLPBaselineRun",
    "ModelSearchSummary",
    "ModelScoreFrames",
    "RANDOM_FOREST_MODEL_NAME",
    "RandomForestBaselineRun",
    "RandomForestConfig",
    "SEARCH_REFIT_METRICS",
    "SearchConfig",
    "SplitConfig",
    "DEFAULT_MODEL_COMPARISON_OUTPUT_DIR",
    "DEFAULT_SNAPSHOT_OUTPUT_DIR",
    "DEFAULT_SNAPSHOT_TOP_K",
    "build_classwise_metrics_frame",
    "build_comparison_classwise_frame",
    "build_comparison_markdown",
    "build_comparison_summary_frame",
    "build_search_summary_frame",
    "build_contrastive_param_grid",
    "build_legacy_gaussian_param_grid",
    "build_mlp_param_grid",
    "build_sklearn_search_scoring",
    "build_stratified_kfold",
    "build_stratify_labels",
    "build_metrics_frame",
    "build_snapshot_markdown",
    "build_snapshot_summary_frame",
    "build_snapshot_top_frame",
    "evaluate_search_metric",
    "fit_legacy_gaussian_baseline",
    "fit_legacy_gaussian_baseline_with_search",
    "fit_mlp_baseline",
    "fit_mlp_baseline_with_search",
    "fit_main_contrastive_model",
    "fit_main_contrastive_model_with_search",
    "fit_random_forest_baseline",
    "load_and_split_benchmark_dataset",
    "load_benchmark_dataset",
    "precision_at_k",
    "prepare_benchmark_dataset",
    "precision_at_k_from_proba",
    "rank_search_metric",
    "run_legacy_gaussian_baseline",
    "run_manual_model_search",
    "run_mlp_baseline",
    "run_main_contrastive_model",
    "run_random_forest_baseline",
    "run_snapshot_comparison",
    "save_comparison_artifacts",
    "save_snapshot_artifacts",
    "search_mlp_for_class",
    "score_main_contrastive_model",
    "score_mlp_baseline",
    "score_random_forest_baseline",
    "score_legacy_gaussian_baseline",
    "split_benchmark_dataset",
    "SnapshotComparisonResult",
    "SnapshotModelRun",
    "normalize_search_score",
    "validate_cross_validation_inputs",
    "validate_scored_frame",
]
