"""Публичный API heavy validation слоя для generalization-аудита."""

from analysis.model_validation.cli import (
    FAST_MODE_RANDOM_STATES,
    FULL_MODE_RANDOM_STATES,
    ModelValidationRunResult,
    build_protocol_from_args,
    main,
    parse_args,
    run_model_validation,
    run_model_validation_scaffold,
)
from analysis.model_validation.contracts import (
    VALIDATION_MODES,
    ModelValidationArtifactPaths,
    ModelValidationLayoutResult,
    ModelValidationProtocol,
    ModelValidationRunRequest,
    ModelValidationSplitResult,
    RepeatedSplitConfig,
    RepeatedSplitEvaluationResult,
    ValidationMode,
)
from analysis.model_validation.generalization_summary import (
    CANONICAL_STAGE_ORDER,
    build_gap_diagnostics_frame,
    build_generalization_stage_frame,
    build_generalization_summary_frame,
)
from analysis.model_validation.layout import (
    DEFAULT_MODEL_VALIDATION_OUTPUT_DIR,
    build_model_validation_artifact_paths,
    initialize_model_validation_layout,
)
from analysis.model_validation.repeated_splits import (
    PRIMARY_METRIC_DIRECTIONS,
    build_repeated_split_model_summary,
    build_repeated_splits_frame,
    build_split_protocol,
    run_repeated_split_evaluation,
    run_validation_split,
)
from analysis.model_validation.reporting import (
    build_model_validation_markdown,
    build_validation_layout_markdown,
    save_model_validation_artifacts,
)
from analysis.model_validation.risk_audit import (
    AVG_GAP_FAIL_THRESHOLD,
    AVG_GAP_WARNING_THRESHOLD,
    CV_STD_FAIL_THRESHOLD,
    CV_STD_WARNING_THRESHOLD,
    LOW_MAX_RISK_SCORE,
    MAX_GAP_FAIL_THRESHOLD,
    MAX_GAP_WARNING_THRESHOLD,
    MODERATE_MAX_RISK_SCORE,
    TEST_RANGE_FAIL_THRESHOLD,
    TEST_RANGE_WARNING_THRESHOLD,
    TEST_STD_FAIL_THRESHOLD,
    TEST_STD_WARNING_THRESHOLD,
    build_model_risk_audit_frame,
    calibration_status_from_brier,
    risk_level_from_score,
    score_threshold_risk,
)

__all__ = [
    "AVG_GAP_FAIL_THRESHOLD",
    "AVG_GAP_WARNING_THRESHOLD",
    "DEFAULT_MODEL_VALIDATION_OUTPUT_DIR",
    "CV_STD_FAIL_THRESHOLD",
    "CV_STD_WARNING_THRESHOLD",
    "FAST_MODE_RANDOM_STATES",
    "ModelValidationArtifactPaths",
    "ModelValidationLayoutResult",
    "ModelValidationProtocol",
    "ModelValidationRunRequest",
    "ModelValidationRunResult",
    "ModelValidationSplitResult",
    "FULL_MODE_RANDOM_STATES",
    "CANONICAL_STAGE_ORDER",
    "LOW_MAX_RISK_SCORE",
    "MAX_GAP_FAIL_THRESHOLD",
    "MAX_GAP_WARNING_THRESHOLD",
    "MODERATE_MAX_RISK_SCORE",
    "PRIMARY_METRIC_DIRECTIONS",
    "RepeatedSplitEvaluationResult",
    "RepeatedSplitConfig",
    "TEST_RANGE_FAIL_THRESHOLD",
    "TEST_RANGE_WARNING_THRESHOLD",
    "TEST_STD_FAIL_THRESHOLD",
    "TEST_STD_WARNING_THRESHOLD",
    "VALIDATION_MODES",
    "ValidationMode",
    "build_model_validation_artifact_paths",
    "build_gap_diagnostics_frame",
    "build_generalization_stage_frame",
    "build_generalization_summary_frame",
    "build_model_validation_markdown",
    "build_model_risk_audit_frame",
    "build_protocol_from_args",
    "build_repeated_split_model_summary",
    "build_repeated_splits_frame",
    "build_split_protocol",
    "build_validation_layout_markdown",
    "calibration_status_from_brier",
    "initialize_model_validation_layout",
    "main",
    "parse_args",
    "risk_level_from_score",
    "run_model_validation",
    "run_repeated_split_evaluation",
    "run_model_validation_scaffold",
    "run_validation_split",
    "score_threshold_risk",
    "save_model_validation_artifacts",
]
