"""Фасад совместимости для пакета host-модели.

Что делает модуль:
    - реэкспортирует публичный API пакета `host_model`;
    - сохраняет совместимость со старыми импортами вида
      `from model_gaussian import ...`;
    - оставляет прежнюю CLI-точку входа через `main()`.

Где находится основная логика:
    - контракты артефактов: `host_model.artifacts`;
    - обучение моделей: `host_model.fit`;
    - scoring: `host_model.legacy_score`,
      `host_model.contrastive_score`;
    - загрузка данных: `host_model.db`.

Что модуль не делает:
    - не содержит собственной реализации host-scoring;
    - не является каноническим местом для новой логики;
    - нужен в первую очередь для обратной совместимости.
"""

from __future__ import annotations

from host_model import (
    CONTRASTIVE_POPULATION_COLUMN,
    CONTRASTIVE_VIEW_ENV,
    DEFAULT_CONTRASTIVE_FIELD_VIEW,
    DEFAULT_CONTRASTIVE_HOST_VIEW,
    DWARF_CLASSES,
    EPS,
    FEATURES,
    LOGG_DWARF_MIN,
    M_EARLY_MAX,
    M_EARLY_MIN,
    M_LATE_MAX,
    M_MID_MAX,
    M_MID_MIN,
    ContrastiveClassParams,
    ContrastiveGaussianModel,
    ContrastiveModelMeta,
    ContrastivePopulationParams,
    ContrastiveScoreResult,
    HostModelArtifact,
    LegacyClassParams,
    LegacyGaussianModel,
    LegacyModelMeta,
    ScoreResult,
    build_contrastive_subsets,
    choose_m_subclass_label,
    contrastive_host_posterior,
    cov_sample,
    fit_contrastive_gaussian_model,
    fit_gaussian_model,
    fit_population_gaussian,
    gaussian_log_likelihood,
    has_missing_values,
    is_contrastive_model,
    is_missing_scalar,
    load_contrastive_model,
    load_contrastive_training_from_db,
    load_default_contrastive_training_from_db,
    load_dwarfs_from_db,
    load_model,
    mahalanobis_distance,
    main,
    make_engine_from_env,
    normalize_host_flag,
    parse_args,
    population_log_likelihood,
    prepare_contrastive_training_df,
    require_contrastive_scoring_model,
    require_legacy_scoring_model,
    resolve_contrastive_label,
    resolve_contrastive_view_name,
    save_model,
    score_df,
    score_df_all_classes,
    score_df_contrastive,
    score_one,
    score_one_all_classes,
    score_one_contrastive,
    shrink_covariance,
    similarity_from_distance,
    split_m_subclasses,
    stabilize_covariance,
    validate_host_model_artifact,
    zscore_apply,
    zscore_fit,
)

__all__ = [
    "CONTRASTIVE_POPULATION_COLUMN",
    "CONTRASTIVE_VIEW_ENV",
    "DEFAULT_CONTRASTIVE_FIELD_VIEW",
    "DEFAULT_CONTRASTIVE_HOST_VIEW",
    "DWARF_CLASSES",
    "EPS",
    "FEATURES",
    "LOGG_DWARF_MIN",
    "M_EARLY_MAX",
    "M_EARLY_MIN",
    "M_LATE_MAX",
    "M_MID_MAX",
    "M_MID_MIN",
    "ContrastiveClassParams",
    "ContrastiveGaussianModel",
    "ContrastiveModelMeta",
    "ContrastivePopulationParams",
    "ContrastiveScoreResult",
    "HostModelArtifact",
    "LegacyClassParams",
    "LegacyGaussianModel",
    "LegacyModelMeta",
    "ScoreResult",
    "build_contrastive_subsets",
    "choose_m_subclass_label",
    "contrastive_host_posterior",
    "cov_sample",
    "fit_contrastive_gaussian_model",
    "fit_gaussian_model",
    "fit_population_gaussian",
    "gaussian_log_likelihood",
    "has_missing_values",
    "is_contrastive_model",
    "is_missing_scalar",
    "load_contrastive_model",
    "load_contrastive_training_from_db",
    "load_default_contrastive_training_from_db",
    "load_dwarfs_from_db",
    "load_model",
    "main",
    "make_engine_from_env",
    "mahalanobis_distance",
    "normalize_host_flag",
    "parse_args",
    "population_log_likelihood",
    "prepare_contrastive_training_df",
    "require_contrastive_scoring_model",
    "require_legacy_scoring_model",
    "resolve_contrastive_label",
    "resolve_contrastive_view_name",
    "save_model",
    "score_df",
    "score_df_all_classes",
    "score_df_contrastive",
    "score_one",
    "score_one_all_classes",
    "score_one_contrastive",
    "shrink_covariance",
    "similarity_from_distance",
    "split_m_subclasses",
    "stabilize_covariance",
    "validate_host_model_artifact",
    "zscore_apply",
    "zscore_fit",
]


if __name__ == "__main__":
    main()
